global using System;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.IO;
global using System.Threading.Tasks;
global using Genealogy.Business.Models.App;
global using Genealogy.Business.Services;
global using Genealogy.Common;
global using Genealogy.Objects.Entities;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using static velocist.Services.Log.StaticLoggerFactory;